2018.7.24

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -337,33 +337,24 @@ MODPATH=$TMP_MODPATH
 
 # Find MODPATH
 if $BOOTMODE; then
-	for loop_device in /dev/block/loop*; do
-		if losetup $loop_device 2>/dev/null | grep -q '\(/data/.*magisk.img\)'; then
-			for MountPoint in $(grep $loop_device /proc/mounts | awk '{print $2}' | grep -v '/system'); do
-				if [ -d "$MountPoint/.core" ] || [ -d "$MountPoint/lost+found" ]; then
-					MountPoint=$MountPoint
-					MODPATH=$MountPoint/$MODID
-					mkdir -p $MODPATH 2>/dev/null
-					break 2
-				fi
-			done
-		fi
-	done
+  for MountPoint in /sbin/.core/img /magisk; do
+    if [ -d "$MountPoint/.core" ] || [ -d "$MountPoint/lost+found" ]; then
+      MountPoint=$MountPoint
+      MODPATH=$MountPoint/$MODID
+      mkdir -p $MODPATH 2>/dev/null
+      break
+    fi
+  done
 
-	if [ ! -d "$MountPoint" ]; then
-		ui_print " "
-		ui_print "(!) Magisk mount point not found"
-		ui_print " "
+	if [ ! -d "$MODPATH" ]; then
+		echo -e "(!) Magisk mount point not found"
 		exit 1
 	fi
 
   if ! is_mounted $MountPoint; then
-    ui_print " "
-	ui_print "(!) Magisk is not activated!... abort"
-    ui_print " "
-	exit 1
+    ui_print "(!) Magisk is not activated!... abort"
+    exit 1
   fi
-
 fi
 
 ##########################################################################################
@@ -572,7 +563,7 @@ mount_check /system
 NewPersistPath=$TMP_MODPATH/.persist
 NewSystemPath=$TMP_MODPATH/system
 NewVendorPath=$NewSystemPath/vendor
-mkdir $NewPersistPath 2>/dev/null
+mkdir $NewPersistPath /persist 2>/dev/null
 mkdir $NewSystemPath
 umount -l /persist 2>/dev/null
 mount_check /persist
